import type { Metadata } from 'next';
import { Geist, Geist_Mono, Lexend } from 'next/font/google';
import Image from 'next/image';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const lexend = Lexend({
  variable: '--font-lexend',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lexend.variable} relative antialiased w-full h-screen`}
      >
        <div className='fixed top-0 left-0 w-full h-full -z-[9999]'>
          <Image
            src='/KoumeiFull.webp'
            alt='Koumei Full'
            fill
            className='-z-[9999]'
            style={{ objectFit: 'cover' }}
          />
        </div>
        <div className='fixed top-0 left-0 size-full bg-black/80 -z-[9998]' />
        {children}
      </body>
    </html>
  );
}
